### ISSUE TITLE
Temporary switch to AWMC as background tiles

### ISSUE THREAD

**Issue by klokan** [klokantech/roman-empire#25]
I am keen to develop a fully vector-based map - integrating OpenMapTiles and our contour lines and hillshading. For now, we use in the background the raster tiles made from DARE data:

https://github.com/klokantech/dare-raster-tiles

But it is a temporary solution, independent of hosting with with data quality issues and incomplete world coverage.

@johaahlf - what about to display now in the background the raster tiles from AWMC?
What is your thinking about this?

They are claimed to be completely free for use and CC-BY licensed:
http://awmc.unc.edu/wordpress/tiles/map-tile-information

A demo of how it would look:

http://labs.klokantech.com/klokan/roman-empire-awmc/#3.96/39.01/21.14

**Comment by johaahlf** [comment]
Hi Petr,
I am in favour of this solution. The tiles of AWMC also have issues with waterways and lakes since it is a digitization of the Barrington Atlas at 1:1 miilon or 1:500k scale. But as a "temporary" solution I approve. The demo looks nice. We still provide the historcial content for the Ancient world. When you get back we can discuss the long term solution in the light of your networking in SF.

**Comment by klokan** [comment]
Done
